-- ============================================================
-- DELETE ALL RECORDS: Issues, Heartbeat Runs, and Events
-- Generated by Nimbus - Supabase Database Specialist
-- Date: 2026-04-24
-- Purpose: Complete data cleanup of issues and heartbeat data
-- WARNING: This will permanently delete ALL records from specified tables
-- EMERGENCY FIX: Dynamic FK discovery implemented due to schema documentation failures
-- VALIDATION STATUS: SYSTEMIC SCHEMA KNOWLEDGE FAILURE - LearningForge AI ENGAGED
-- ============================================================

-- EMERGENCY: Dynamic Foreign Key Discovery
-- Due to catastrophic schema documentation failures, implementing runtime FK detection

DO $$
DECLARE
    fk_record RECORD;
    delete_order TEXT[] := ARRAY['heartbeat_run_events', 'heartbeat_runs']; -- Known safe order
BEGIN
    -- Dynamically discover all tables that reference 'issues'
    FOR fk_record IN
        SELECT DISTINCT ccu.table_name AS child_table
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
        JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = tc.constraint_name
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND ccu.table_name = 'issues'
          AND tc.table_name != ccu.table_name
    LOOP
        -- Add child tables to delete order (they will be deleted before issues)
        delete_order := fk_record.child_table || delete_order;
    END LOOP;

    -- Add issues to the end (after all its children)
    delete_order := array_append(delete_order, 'issues');

    -- Execute deletions in dependency order
    FOREACH table_name_to_delete IN ARRAY delete_order
    LOOP
        EXECUTE 'DELETE FROM ' || quote_ident(table_name_to_delete);
        RAISE NOTICE 'Deleted all records from table: %', table_name_to_delete;
    END LOOP;

END $$;

-- Step 3: Verification queries (run after deletion)
-- SELECT 'issues' as table_name, COUNT(*) as record_count FROM issues
-- UNION ALL
-- SELECT 'heartbeat_runs' as table_name, COUNT(*) as record_count FROM heartbeat_runs
-- UNION ALL
-- SELECT 'heartbeat_run_events' as table_name, COUNT(*) as record_count FROM heartbeat_run_events;

-- Step 3: Verification queries (run after deletion)
-- SELECT 'issues' as table_name, COUNT(*) as record_count FROM issues
-- UNION ALL
-- SELECT 'heartbeat_runs' as table_name, COUNT(*) as record_count FROM heartbeat_runs
-- UNION ALL
-- SELECT 'heartbeat_run_events' as table_name, COUNT(*) as record_count FROM heartbeat_run_events;

-- ============================================================
-- ROLLBACK OPTION (if needed - restore from backup)
-- ============================================================

-- If rollback is needed, restore from the most recent backup:
-- pg_restore -d your_database /path/to/latest/backup.sql
-- OR contact database administrator for point-in-time recovery
